version: '3.3'

services:
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: dodderjs
      MONGODB_PASS: supersecretPassword12345
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
      - ./data/hw1-1/dump:/data/dump1
      - ./data/hw1-2/dump:/data/dump2
      - ./data/hw1-3/dump:/data/dump3
    command: --smallfiles --logpath=/dev/null # --quiet

  app:
    build: ./app
    image: mdb-app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3302:3302"
    command: ["./wait-for-it.sh", "database:27017", "--", "npm", "start"]
    depends_on:
      - database
    environment:
      NODE_ENV: development
      NODE_ENV_PORT: 3302
      DB_HOST: database
      DB_PORT: 27017
      DB_USER: dodderjs
      DB_USER_PASS: supersecretPassword12345
